# Generated by Django 5.2.1 on 2026-04-05 17:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Track",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("track_id", models.CharField(max_length=120, unique=True)),
                ("title", models.CharField(max_length=200)),
                ("artist", models.CharField(blank=True, max_length=200)),
                (
                    "source",
                    models.CharField(
                        choices=[("local", "Local Library"), ("spotify", "Spotify")],
                        default="local",
                        max_length=20,
                    ),
                ),
                ("preview_url", models.URLField(blank=True)),
                ("stream_url", models.URLField(blank=True)),
                ("image_url", models.URLField(blank=True)),
                ("valence", models.FloatField(default=0.5)),
                ("energy", models.FloatField(default=0.5)),
                ("duration_seconds", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="MusicSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_key", models.CharField(max_length=80)),
                ("queue_track_ids", models.JSONField(default=list)),
                ("current_index", models.PositiveIntegerField(default=0)),
                (
                    "playback_state",
                    models.CharField(
                        choices=[
                            ("playing", "Playing"),
                            ("paused", "Paused"),
                            ("stopped", "Stopped"),
                        ],
                        default="paused",
                        max_length=20,
                    ),
                ),
                ("current_time_seconds", models.FloatField(default=0.0)),
                ("volume", models.FloatField(default=0.8)),
                ("last_mood", models.CharField(blank=True, max_length=30)),
                ("last_mood_shift_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="music_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "current_track",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="active_sessions",
                        to="music.track",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
                "unique_together": {("user", "session_key")},
            },
        ),
    ]
