# Generated by Django 5.2.11 on 2026-02-17 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APIUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_type', models.CharField(choices=[('openai', 'OpenAI'), ('google_speech', 'Google Speech'), ('google_translate', 'Google Translate'), ('azure_emotion', 'Azure Emotion'), ('other', 'Other')], max_length=20)),
                ('endpoint', models.CharField(max_length=200)),
                ('request_data', models.JSONField(blank=True, null=True)),
                ('response_data', models.JSONField(blank=True, null=True)),
                ('tokens_used', models.IntegerField(blank=True, null=True)),
                ('response_time', models.FloatField(blank=True, null=True)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_level', models.CharField(choices=[('debug', 'Debug'), ('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], max_length=10)),
                ('module', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('stack_trace', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='UserStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_messages', models.IntegerField(default=0)),
                ('total_tasks_created', models.IntegerField(default=0)),
                ('total_tasks_completed', models.IntegerField(default=0)),
                ('total_voice_inputs', models.IntegerField(default=0)),
                ('total_camera_uses', models.IntegerField(default=0)),
                ('total_active_time', models.IntegerField(default=0)),
                ('average_session_duration', models.IntegerField(default=0)),
                ('conversation_count', models.IntegerField(default=0)),
                ('average_sentiment', models.FloatField(default=0.0)),
                ('dominant_emotion', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
