# Generated by Django 5.2.11 on 2026-02-17 17:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BehaviorPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern_type', models.CharField(choices=[('routine', 'Routine'), ('habit', 'Habit'), ('trend', 'Trend'), ('anomaly', 'Anomaly')], max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('frequency', models.CharField(max_length=50)),
                ('time_of_day', models.TimeField(blank=True, null=True)),
                ('day_of_week', models.IntegerField(blank=True, null=True)),
                ('confidence_score', models.FloatField()),
                ('occurrence_count', models.IntegerField(default=0)),
                ('last_occurred', models.DateTimeField(blank=True, null=True)),
                ('pattern_data', models.JSONField(blank=True, null=True)),
                ('first_detected', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behavior_patterns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-confidence_score', '-last_updated'],
            },
        ),
        migrations.CreateModel(
            name='EmotionState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emotion', models.CharField(choices=[('happy', 'Happy'), ('sad', 'Sad'), ('angry', 'Angry'), ('fearful', 'Fearful'), ('surprised', 'Surprised'), ('disgusted', 'Disgusted'), ('neutral', 'Neutral'), ('excited', 'Excited'), ('anxious', 'Anxious'), ('calm', 'Calm'), ('stressed', 'Stressed'), ('tired', 'Tired')], max_length=20)),
                ('intensity', models.FloatField()),
                ('source', models.CharField(choices=[('text', 'Text Analysis'), ('voice', 'Voice Tone'), ('facial', 'Facial Expression'), ('combined', 'Combined Sources')], max_length=10)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('context_description', models.TextField(blank=True, null=True)),
                ('text_content', models.TextField(blank=True, null=True)),
                ('voice_features', models.JSONField(blank=True, null=True)),
                ('facial_features', models.JSONField(blank=True, null=True)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('model_version', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emotion_states', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='FacialEmotionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_file', models.ImageField(blank=True, null=True, upload_to='facial_analysis/')),
                ('primary_emotion', models.CharField(max_length=20)),
                ('primary_confidence', models.FloatField()),
                ('secondary_emotion', models.CharField(blank=True, max_length=20, null=True)),
                ('secondary_confidence', models.FloatField(blank=True, null=True)),
                ('facial_landmarks', models.JSONField(blank=True, null=True)),
                ('face_position', models.JSONField(blank=True, null=True)),
                ('smile_intensity', models.FloatField(default=0.0)),
                ('eye_contact', models.BooleanField(default=False)),
                ('head_pose', models.JSONField(blank=True, null=True)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('model_version', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facial_emotions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='VoiceToneAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.FileField(upload_to='voice_analysis/')),
                ('duration', models.FloatField()),
                ('pitch_average', models.FloatField(blank=True, null=True)),
                ('pitch_variance', models.FloatField(blank=True, null=True)),
                ('speech_rate', models.FloatField(blank=True, null=True)),
                ('volume_average', models.FloatField(blank=True, null=True)),
                ('detected_emotion', models.CharField(max_length=20)),
                ('emotion_confidence', models.FloatField()),
                ('voice_stress_level', models.FloatField(default=0.0)),
                ('hesitation_count', models.IntegerField(default=0)),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('transcription', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-analyzed_at'],
            },
        ),
        migrations.CreateModel(
            name='EmotionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('happy_percentage', models.FloatField(default=0.0)),
                ('sad_percentage', models.FloatField(default=0.0)),
                ('angry_percentage', models.FloatField(default=0.0)),
                ('anxious_percentage', models.FloatField(default=0.0)),
                ('neutral_percentage', models.FloatField(default=0.0)),
                ('other_percentage', models.FloatField(default=0.0)),
                ('dominant_emotion', models.CharField(max_length=20)),
                ('average_intensity', models.FloatField()),
                ('emotion_changes_count', models.IntegerField(default=0)),
                ('emotional_stability_score', models.FloatField(default=0.0)),
                ('stress_level', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emotion_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('chat', 'Chat Message'), ('task_create', 'Task Created'), ('task_complete', 'Task Completed'), ('voice_input', 'Voice Input'), ('camera_access', 'Camera Access'), ('settings_change', 'Settings Change'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('activity_data', models.JSONField(blank=True, null=True)),
                ('emotional_state', models.CharField(blank=True, max_length=20, null=True)),
                ('device_info', models.JSONField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'activity_type', 'timestamp'], name='emotion_tra_user_id_147598_idx')],
            },
        ),
    ]
