# Generated by Django 5.2.4 on 2026-02-21 06:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat_companion", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="cognitive_impact",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="message",
            name="explanation",
            field=models.TextField(blank=True, null=True),
        ),
    ]
